base_url = "https://www.juricho.me"
title = "Juri Chom√©"
default_language = "en"
generate_feeds = true

[markdown]
external_links_target_blank = true
bottom_footnotes = true

[markdown.highlighting]
theme = "github-light"

[extra]
github_edit_url = "https://github.com/2mol/juricho.me/edit/main/content/"
base_url_simple = "juricho.me"
