base_url = "https://www.juricho.me"
title = "Juri Chom√©"
default_language = "en"
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "demain"

external_links_target_blank = true

[extra]
github_edit_url = "https://github.com/2mol/juricho.me/edit/master/content/"
base_url_simple = "juricho.me"
